Dockerfile

Updated to V3.1.4

---

Dockerfile
Dockerfile.v3.2.x
README.md

Added 3.2.1

---

Dockerfile.v3.2.x

Reverted the disabling of mongodb journaling

---

README.md

Added docs about persistent data permissions; fixes #11

---

Dockerfile.v3.2.x
README.md
entrypoint.sh

Added entrypoint to create directory and add checks

---

Dockerfile.v3.2.x
entrypoint.sh

Updated entrypoint to set permissions and added gosu

---

Dockerfile.v3.2.x

The change adds a check on the status of the Omada controller in the docker container.

Add healthcheck

---

README.md
entrypoint.sh

Added SMALL_FILES env var; fixes #6

---

Dockerfile.v3.2.x

Updated to 3.2.9; fixes #27

---

Dockerfile.v3.2.x-arm64

Updated to v3.2.9 for rpi

---

Dockerfile.v3.2.x-arm64

Optimize arm64 Dockerfile

---

Dockerfile.v3.2.x-arm64

More optimization to the arm64 build

---

Dockerfile.v3.2.x
Dockerfile.v3.2.x-arm64

Updated to v3.2.10

---

README.md

Updated version in README; fixes #34

---

Dockerfile.v3.2.x
Dockerfile.v3.2.x-arm64

Fixed healthcheck to not save file; changed output; fixes #38

---

Dockerfile.v3.2.x-armv7l

Added armv7l image; fixes #31

---

Dockerfile.v3.2.x
README.md
entrypoint.sh

Allow to configure custom certificates, i.e. issued by a private CA

Support Custom Certs

---

.gitignore
Dockerfile
Dockerfile.v4.1.x
README.md
entrypoint-4.1.x.sh

Added 4.1.x support

---

Dockerfile.v4.1.x-arm64

Added v4.1-arm64

---

Dockerfile.v4.1.x-armv7l

Added v4.1.x-armv7l

---

README.md

Updated README for arm v4.1 images

---

README.md

Updated readme to reflect 4.2.x images

---

Dockerfile.v4.2.x
Dockerfile.v4.2.x-armv7l
README.md

Updated to 4.2.8

---

Dockerfile.v3.2.x
Dockerfile.v3.2.x-arm64
Dockerfile.v3.2.x-armv7l
README.md

Updated 3.2.10 -> 3.2.14

---

Dockerfile.v4.2.x
Dockerfile.v4.2.x-armv7l

to reduce hard-coded values in the code below and try to facilitate
upgrade to next versions
Signed-off-by: Fabrice Aeschbacher <fabrice.aeschbacher@gmail.com>

Make use of ARG in Dockerfile

---

Dockerfile.v4.2.x

Updated 4.2.x to 4.2.11

---

README.md

Added back examples for port mapping; documents / fixes #66

---

Dockerfile.v4.1.x
Dockerfile.v4.1.x-armv7l
Dockerfile.v4.2.x
healthcheck.sh

Added healthcheck script; fixes #87

---

README.md

Updated README with a note about the port mapping issue; fixes #99

---

Dockerfile
Dockerfile.v4.3.x
README.md
docker-compose.yml
entrypoint-4.3.x.sh

Added 4.3.5; fixes #102

---

README.md

Updated readme; fixes #106

---

README.md
entrypoint-4.x.sh

Updated README; removed warning in entrypoint

---

Dockerfile
Dockerfile.v4.4.x
README.md
install.sh

Added 4.4.3

---

README.md

Updated README for multi-arch; fixes #122

---

Dockerfile.v4.4.x

4.4.4 is out, this branch adds support for it.

Support for 4.4.4

---

README.md

4.4.4 has been released and fixes a number of bugs, readme is updated to reflect that.

Updated readme.md to reflect 4.4.4 release

---

install.sh

Fixes #127; addresses how to deal with inconsistent builds

---

Dockerfile.v4.4.x
README.md
install.sh

Updates for 4.4.6; fixes #132

---

README.md

Updated README to reference 4.4 instead of 4.3

---

entrypoint-4.x.sh

Added check for /tmp permissions

---

entrypoint-3.2.sh

Backport /tmp for 3.2

---

Dockerfile.v3.0.x
Dockerfile.v3.1.x
Dockerfile.v3.2.x
Dockerfile.v3.2.x-arm64
Dockerfile.v3.2.x-armv7l
Dockerfile.v4.1.x
Dockerfile.v4.1.x-armv7l
Dockerfile.v4.2.x
Dockerfile.v4.3.x
Dockerfile.v4.4.x
log4j_patch.sh

Added log4j patch to all versions; fixes #143

---

log4j_patch.sh

https://github.com/mbentley/docker-omada-controller/issues/143#issuecomment-995379538

Bump log4j to 2.16.0

---

entrypoint-3.2.sh
entrypoint-4.x.sh

Update how keystore is imported to use standard format

---

Dockerfile.v4.4.x
README.md
install.sh

Upgrade to 4.4.8; fixes #147

---

Dockerfile.v4.4.x

No need to patch log4j

---

Dockerfile.v4.4.x
log4j_patch.sh

Handles https://github.com/mbentley/docker-omada-controller/issues/143#issuecomment-997269504

Get latest log4j version automatically; d/l from archive

---

Dockerfile.v3.2.x-arm64
Dockerfile.v4.1.x
Dockerfile.v4.1.x-armv7l

Upgrade java version; no reason to pin it; shell fixes

---

log4j_patch.sh

Added signature checking of log4j binaries

---

log4j_patch.sh

Added removal of key info

---

log4j_patch.sh

Attempt to fix the log4j checksum inconsistency yet again

---

Dockerfile
Dockerfile.v5.0.x
README.md
docker-compose.yml
entrypoint-5.x.sh
install.sh

Added 5.0.29; update README; fixes #155

---

README.md

Updated examples; fixes #163

---

Dockerfile.v5.0.x
README.md

Upgraded 5.0 to 5.0.30; fixes #172

---

README.md
entrypoint-5.x.sh

Added doc details about portainer; addresses #174

---

Dockerfile.v3.2.x
Dockerfile.v3.2.x-arm64
Dockerfile.v3.2.x-armv7l
README.md

Updated 3.2.x to 3.2.16

---

README.md

Fixed the amd64 specific tags listed in the readme

---

README.md

Updated README version with tables

---

Dockerfile
Dockerfile.v5.1.x
README.md
docker-compose.yml

Bumped for 5.1.17; fixes #191

---

README.md
entrypoint-3.2.sh

Added custom ports for management interfaces; fixes #195

---

Dockerfile.v5.3.x
README.md
entrypoint-5.x.sh
install.sh

Added 5.3.1; fixes #201

---

Dockerfile.v5.0.x
Dockerfile.v5.1.x
Dockerfile.v5.3.x

Updated to Ubuntu 20.04 for 5.x; fixes #200

---

KNOWN_ISSUES.md
entrypoint-5.x.sh

Update URL to upgrade issue docs; clarify update note; fixes #205

---

install.sh

Updated the version of Java used by the 5.x versions

---

install.sh

Reverts mbentley/docker-omada-controller#208

Revert "Updated the version of Java used by the 5.x versions"

---

Dockerfile.v3.2.x
Dockerfile.v3.2.x-arm64
Dockerfile.v3.2.x-armv7l
Dockerfile.v4.1.x
Dockerfile.v4.1.x-armv7l
README.md
docker-compose.yml
entrypoint-3.2.sh
entrypoint-4.x.sh
entrypoint-5.x.sh
install.sh

Added PUID/PGID env vars to set UID/GID at runtime; fixes #212

---

Dockerfile.v5.3.x-chromium
entrypoint-5.x.sh
install.sh

Added fixes for persistent data issues related to reports

---

install.sh

Added check to make sure directory exists before tarring

---

README.md

Fix build instructions; fixes #219

---

Dockerfile
Dockerfile.chromium
Dockerfile.v5.4.x
README.md
docker-compose.yml
install.sh

Added 5.4.6; fixes #221

---

entrypoint-5.x.sh

Fixed entrypoint to handle new openjdk 17

---

Dockerfile.v4.x
Dockerfile.v5.x
entrypoint-4.x.sh
entrypoint-5.x.sh
install.sh

Added version check; prevents user from running an older version

---

Dockerfile.v5.x
README.md
docker-compose.yml
entrypoint-5.x.sh
install.sh

Removed work directory from 5.x

---

README.md

Updated readme to have note about work in bullet list

---

Dockerfile.v3.2.x
Dockerfile.v3.2.x-arm64
Dockerfile.v3.2.x-armv7l
README.md

Updates for 3.2.17; fixes #234

---

README.md

Moved 4.2 and 4.3 to archived; fixes #232

---

README.md

Added upgrade path docs

---

Dockerfile.v3.0.x
Dockerfile.v3.1.x
Dockerfile.v5.x
README.md
docker-compose.yml
install.sh
log4j_patch.sh

Added 5.5; updated log4j with specific versions to patch; fixes #239

---

Dockerfile.v3.0.x
Dockerfile.v3.1.x
Dockerfile.v3.2.x
Dockerfile.v3.2.x-arm64
Dockerfile.v3.2.x-armv7l

Add fixes to always run log4j patch script

---

Dockerfile.v3.0.x
Dockerfile.v3.1.x
Dockerfile.v3.2.x
Dockerfile.v3.2.x-arm64
Dockerfile.v3.2.x-armv7l

Added INSTALL_VER for older builds

---

Dockerfile.chromium

Changed to use PPA for chromium; fixes #214

---

Dockerfile.chromium
README.md

Updated chrome to use different PPA; added docs

---

README.md
docker-compose.yml
entrypoint-5.x.sh
install.sh

Added capability for setting omada service custom ports

Added capability for setting omada service custom ports

---

Dockerfile.v5.x
README.md
docker-compose.yml
install.sh

Added support for 5.6.3; fixes #254

---

docker-compose.yml

Added 60s grace period for stop; fixes #260

---

Dockerfile.v5.x
README.md
docker-compose.yml
install.sh

Added support for 5.7.4; fixes #264

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Added version number information to bug reports

---

Dockerfile.v5.x
README.md
docker-compose.yml
install.sh

Added 5.8.4; fixes #277

---

KNOWN_ISSUES.md
README.md

Added upgrade known issue; fixes #282

---

KNOWN_ISSUES.md
README.md
entrypoint-3.2.sh
entrypoint-4.x.sh
entrypoint-5.x.sh

Adds userland/kernel check + known issue about rpi4 devices

---

Dockerfile.v5.x
entrypoint-5.x.sh
external_mongodb/README.md
external_mongodb/omada.js
install.sh

This is still somewhat a WIP to address #356

Experimental external mongodb

---

Dockerfile.v5.x

Reverts mbentley/docker-omada-controller#384

Revert "Added JVM arg to allow restore to function; fixes #383"

---

README.md
install.sh

Had to switch to `awk` for more consistent version parsing since they added a 4th version value in this beta version

Updates for the latest beta

---

README.md
README_v3_and_v4.md

Part of https://github.com/mbentley/docker-omada-controller/issues/435

Consolidated v3/v4 information into a single file

---

external_mongodb/README copy.md
external_mongodb/README.md
external_mongodb/kubernetes/mongodb/Chart.yaml
external_mongodb/kubernetes/mongodb/templates/_helpers.tpl
external_mongodb/kubernetes/mongodb/templates/external-secrets.yaml
external_mongodb/kubernetes/mongodb/values-customized.yaml
external_mongodb/kubernetes/mongodb/values.yaml
external_mongodb/kubernetes/omada-controller/base/configmap-env.yaml
external_mongodb/kubernetes/omada-controller/base/deployment.yml
external_mongodb/kubernetes/omada-controller/base/kustomization.yaml
external_mongodb/kubernetes/omada-controller/base/pvc-omada-data.yml
external_mongodb/kubernetes/omada-controller/base/pvc-omada-logs.yml
external_mongodb/kubernetes/omada-controller/base/service.yml
external_mongodb/kubernetes/omada-controller/production/certificate.yaml
external_mongodb/kubernetes/omada-controller/production/ingress.yml
external_mongodb/kubernetes/omada-controller/production/kustomization.yaml
external_mongodb/kubernetes/omada-controller/production/overlays/service.yml

**Description:**
- Add manifests to deploy Omada Controller in Kubernetes
- Add Helm chart to deploy MongoDB in Kubernetes
- Add documentation of the process
Note: Late but done :) 
Related: https://github.com/mbentley/docker-omada-controller/issues/356#issuecomment-2016462587

docs: How to deploy in Kubernetes

---

Dockerfile.v5.x

Added ports to the dockerfile
